<?xml version="1.0" encoding="UTF-8" ?> 
<testsuites errors="1" 
            failures="0" 
            tests="1"> 
 
  <testsuite name="sandbox" 
    errors="1" failures="0" hostname="" id="" package="sandbox" skipped="0" 
    tests="1" time="0.005000" timestamp="Thu, 27 Jul 2017 19:28:20 GMT"> 
   
    <testcase name="Тестовая дичь" classname="sandbox" time="0.005000" assertions="0"> 
    </testcase> 
      <system-err> 
          Error while running [Sandbox / Тестовая дичь]:

  ReferenceError: a is not defined
    at Object.Тестовая дичь (D:\AT\Autotest\tests\sandbox.js:16:13)
    at Module.call (D:\AT\Autotest\nightwatch\lib\runner\module.js:62:34)
    at D:\AT\Autotest\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (D:\AT\Autotest\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\AT\Autotest\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\AT\Autotest\node_modules\q\q.js:796:13)
    at D:\AT\Autotest\node_modules\q\q.js:556:49
    at runSingle (D:\AT\Autotest\node_modules\q\q.js:137:13)
    at flush (D:\AT\Autotest\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7) 
      </system-err> 
   
   
  </testsuite> 
</testsuites> 
